import streamlit as st
from PIL import Image

st.set_page_config(page_title="Infrastructure in Chicago", layout="wide")

st.title("An Analysis of Chicago Menu Money Expenditure to Reveal the Status of Infrastructure Concerns in Chicago")
st.write("The main aim of this project is to help understand what kind of infrastructure concerns are faced by different wards in Chicago and possible correlates they may reveal.\n")
st.write(
    "Some sub questions we hope to elucidate more on:\n"
    "- **Chicago Menu-Money Spending Over Time**: How have Chicago menu-money spending patterns changed over time. Such an analysis could indicate how different wards have developed over time and the signature concerns faced by wards.\n"
    "- **Correlations with Infrastructure Concerns**: In an effort to characterize what the infrastructure concerns indicate about each neighborhood, we plan to evaluate whether data about resident demographics, tourism, crime or education can reveal patterns in Chicago menu-money spending. \n"
    "- **What does this all mean**: Combining these two approaches could reveal underlying problems in wards providing a rationale for current Chicago menu-money spending habits but also provide another perspective on the history of segregation in Chicago. \n"
)
st.write("On this page, you will information about the dataset, Chicago neighborhoods, community areas and ward, along with a description of the main problem we are trying to address.")
st.write("To get an overview of spending patterns and trends by Chicago side, navigate to the Menu-Money Overview page.")
st.page_link("pages/Menu-Money Overview.py", label="Menu-Money Overview", icon="💰")
st.write("To understand how infrastructure spending patterns reflect in resident quality of life, navigate to the Infrastructure Correlates page.")
st.page_link("pages/Infrastructure Correlates.py", label="Infrastructure Correlates", icon="📊")
st.write("To get some quick take-home messages from this analysis, navigate to the Conclusion page")
st.page_link("pages/Conclusion.py", label="Conclusion", icon="🌆")

st.header("Aldermanic Wards and a Resource-Allocation Problem in Chicago")
st.write("Given the vast cultural and ethnic history of the city of Chicago, the city has been divided into multiple different subdivisions. Chicago is most known as the city of neighborhoods owing to its 77 distinct community areas each representing a vibrant and distinct cultural composition. These community areas were established in the early 1900s based on even distribution of population, income and health statistics. Over time, this tradition of the original community areas has evolved greatly leading to community areas with particularly skewed identities and specific ethnic compositions resulting in an ongoing history of segregation in Chicago. Even more, owing to the specific rigid boundaries between community areas, Chicago neighborhoods are no longer well represented by the community area they are meant to fall under. Instead, Chicago communities tend to form their own neighborhoods regardless of the specific community area they belong in. This results in a certain futility of community areas to mark distinctions between communities in Chicago. While community areas are marked to allow for better urban planning and resource division, their unchanging nature has led to both a maintenance of traditions of segregation in Chicago and their futility in representing distinct “neighborhoods” and community identities. ")
st.write("	While community areas were formed in the early 1900s specifically for municipal management, a great deal of resource allocation and city-wide repairs falls under the jurisdiction of wards. Wards are 50 distinct voting districts in Chicago that are redrawn every 10 years based on census data in efforts to maintain a roughly even population throughout wards. While this would suggest that it could circumvent concerns about changing neighborhoods, the process of redrawing the ward map is opaque and conducted by the biased politicians as opposed to urban planners and sociologists. This can and has led to practices like jerrymandering and created deep inequities in how resources are allocated across the city of Chicago. These political actions have deep societal implications as it biases perceptions about certain Chicago neighborhoods and the demographics that constitute them. Such misconceptions can further ingrain racial stereotypes and advance the tradition of segregation further. ")
st.write("	An example of a resource that the wards are allowed to expend is the Chicago Menu-Money project. Every year, each of the 50 wards in Chicago receive 1.5 Million Dollars to expend on infrastructure in the wards.  The alders of each ward are allowed to spend the money at their own discretion on both menu projects and non-menu projects. Each year, the city of Chicago releases a report containing details of infrastructure expenses by ward in a pdf. This data has historically been impossible to analyze owing to its unreadable release of a poorly formatted pdf document. In 2023, a data scientist, Jake Smith, scraped the pdfs of menu-money spending from 2012-2023 and collated data on each wards spending patterns in a dataset. This dataset provides the first opportunity to scrutinize the way different alders spend money and show key insights on the type of infrastructure concerns faced by different Chicago sides. It also brings political decisions back to masses by allowing residents to analyze their communities needs and provide recommendations to their alders. ")
st.write("	Through this project, we aim to exploit this recently available information on how the infrastructure of the city of Chicago is maintained by distinct wards and provide an analysis of spending patterns by Chicago side. Moreover, we aim to show how the division of wards and drawing of ward boundaries greatly impact the relative value of the Chicago menu-money allocation and how inequities in resource allocation can lead to certain neighborhoods and Chicago sides struggling with crime, safety, poor living conditions and lack of quality of education. Overall, we aim to illustrate some pressing concerns with the formulation of these wards and the lack of suitability of a one-size-fits-all model of menu-money allocation by ward.  ")
st.link_button("Chicago menu-money dataset", "https://github.com/jakejsmith/ChicagoMenuMoney")
st.link_button("Crimes Dataset", "https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2/about_data")
st.link_button("Census Dataset", "https://data.cityofchicago.org/Community-Economic-Development/ACS-5-Year-Data-by-Ward/awnk-6fvc/about_data")
st.link_button("Vehicle Crashes Dataset", "https://data.cityofchicago.org/Transportation/Traffic-Crashes-Crashes/85ca-t3if/about_data")

