import streamlit as st
import altair as alt
from charts.charts_crime import crimefullchart, transporttot, schools_view
st.sidebar.header("Infrastructure Correlates")

st.set_page_config(page_title="Correlates", layout="wide")
st.title("Overview of Chicago Menu-Money Spending Patterns")

st.header("Correlations between race and under-resourced neighborhoods can lead to misconceived stereotypes")
st.subheader("What is the graph below addressing?")
st.write("[Stuart et al (2024)](%s) conducted a sentiment analysis on articles by the Chicago Tribune mentioning one of the 77 Chicago community areas. The sentiment analysis was then used to score the overall reputation of each community area to reflect public perception or media-propagated perception of Chicago neighborhoods. A key finding from this thorough analysis was that the reputation of a neighborhood and their status in a neighborhood hierarchy is negatively related to the proportion of black residents in the neighborhood. Adding on to this concern, they also noted that the strength of this relationship increased with time. The paper reveals the importance of media reporting in forming such perceptions. " % "https://journals.sagepub.com/doi/full/10.1177/00420980241297088")
st.write("Moreover, articles such as [this](%s) listing most “dangerous” neighborhoods in Chicago often strengthen such biases and ignore confounding variables like availability of resources to certain neighborhoods. The graph below shows how public crime rates in Chicago have changed between 2012 and 2023 along with changes in amount of money spent by the city (through the menu-money fund) overall on security cameras. This data is supplemented with a spatial analysis of race demographics, amount of money spent on security cameras per crime per person in each ward in 2021 and the total number of crimes in each ward in 2021." % "https://www.fox32chicago.com/news/chicago-most-dangerous-neighborhoods")
st.altair_chart(crimefullchart, width='content')
st.caption("Figure 2: Racial demographics, security camera spending, and public crime levels in 2021 and combined statistics over time.")
st.write("From looking at the top panel of the above figure we can see that while money spent on security cameras doesn’t precisely correlate with occurrences of public crimes in the Chicago area, it does closely mirror trends. Since 2012, public crimes have decline steadily while spending on security cameras steadily increased. A relationship between them is more closely observable in 2021 where spending on security cameras spiked and occurrences of public crimes dipped. It should be noted that a confounding variable of lack of police presence due to COVID-19 could have motivated the increase in security cameras and the distancing policies could have led to lower crime rates. Regardless, the relationship still illustrates that the purpose of public security cameras deployed by the city is to control crime rates and are a possible response to high crime rates")
st.write("The spatial analysis in purple indicates the distribution of different races across Chicago Wards. Not only does this analysis show how racially segregated Chicago is but also shows how marginalized communities (like African American and Hispanic populations) are even geographically marginalized to city edges. Outlining wards based on the most prevalent race would further suggest, from looking at the blue choropleth, that wards with predominantly African American populations are those with higher instances of public crimes. Such a basic analysis is what leads to misconceived perceptions as those noted earlier. A closer look at infrastructure concerns in these wards reveal that infrastructure and under-resourcing is a major confounding factor when making judgments about crime rates and race. The line graph evidently shows that infrastructure plays a role in influencing crime rates and using the data from the Chicago Menu-Money expenditure we can understand how security camera installment has further skewed crime rates. ")
st.write("The green choropleth shows how much money wards can expend on security cameras relative to the density of crime in the ward. Of the wards with the highest crime rates as seen in the blue choropleth, only two of them are in predominantly White wards. The rest are wards with predominantly African American residents. However, the same two wards (Ward 42 and Ward 27) also have a relatively high amount of money spent on security cameras per crime per person (average = 4.7). Meanwhile, the rest of the wards with relatively high crime counts, which are also predominantly African American have close to no spending on security cameras. While causal roots of this spending pattern is out of the scope of this project, we can see that lack of infrastructure is a major confounding variable when determining markers of “safe” neighborhoods. The analysis of the infrastructure features in the Chicago menu-money dataset was thus able to show how some wards are unable to adequately address pressing infrastructure concerns and suggests that equal division of infrastructure resources among wards (as they are currently drawn) is largely inequitable. ")


st.header('Even though most money is spent on Streets & Transportation + Lighting, the spending is still insufficient for some neighborhoods')
st.write("The previous section clearly indicated that certain neighborhoods are unable to meet the demands of their infrastructure concerns using menu-money alone. From the overview, we saw that these same neighborhoods (South Side, West Side and Far South Side) are unable to spare budget money on non-essential categories. If most of the budget is being allocated to expenditure on Streets & Transportation and Lighting, it begs the question on whether certain wards are over-allocating their resources to street maintenance. To see how the different neighborhoods manage their spending on Streets & Transportation + Lighting, we first looked at whether there were differences in the proportion of the budget spent on the same. Upon conducting this analysis, we noticed that the while the wards are drawn keeping in mind even population distribution, it doesn’t well take into account area leading to some wards being a lot larger than others. Furthermore, the needs of categories like Streets & Transportation and lighting would presumably scale along with size (the bigger the ward, the more streets and roads requiring maintenance). The two bar plots indicate the absolute proportional spending of the wards on the two categories and how the relative proportional spending of the wards normalized by area (in arbitrary relative units). To examine the effects of this resource allocation pattern, we examined a dataset of vehicle crashes from 2012-2023 to see the frequency of accidents caused by defects in the road or due to dark unlit roads. ")
st.altair_chart(transporttot, width='content')
st.caption("Figure 3: Analysis of Vehicle crashes (due to road defects of unlit roads) relative to Streets & Transportation and Lighting spending by neighborhood normalized by area")
st.write("From the chart where we compare menu money allocation relative to ward area, it is clear that the north side receives the largest amount of menu money relative to the ward area. The Far South Side sees the absolute least. Because wards are drawn based on population rather than land area, some of the wards are covering much larger geographic regions, meaning that they likely contain more road infrastructure that would require maintenance. These are not necessarily receiving proportionally more funding, which means that geographically larger wards may struggle to maintain streets and lighting with the same menu money budget. So despite the fact that wards in the South Side and Far South Side are allocating a bigger part of their budget to these two categories, as seen in the bar graph on the left, they are still underallocating resources to the two categories relative to area and to the North Side as seen in the right bar graph.")
st.write("The map of crashes due to road defects shows higher crash rates concentrated in wards in the South and West sides. This pattern is a further indication that the maintenance of roads in these particular wards is insufficient, potentially due to limited menu money. The adjacent map of crashes due to unlit roads shows a similar pattern. It shows the highest crash ratios in the southern wards, especially in the Far South Side. This is especially evident when looking at ward 10. Ward 10 is in the Far South Side and spends roughly 95% of their budget on Streets & Transportation + Lighting. Yet, Ward 10 still has considerably less amount of money spent on lighting and streets relative to other Chicago sides. The amount of money on Lighting is especially noteable. The effects of this inadequate allocation is evident in the incredibly high number of crashes occurring due to unlit roads as opposed to lit roads. In Ward 10, one in every 4 vehicle crashes that occur in the dark are due to unlit roads. This is staggeringly high when compared to a ward like Ward 43 where approximately one in every 7 vehicle crashes that occur in the dark are due to unlit roads. Considering these plots together, we can see a correlation between the smallest amount of menu money allocated to the far south side of Chicago relative to its land area, and the highest crash ratio relative to road infrastructure in both maps. This suggests that an unequal distribution of menu money relative to ward area may contribute to a deficiency in infrastructure, which increases the traffic safety risk of underserved wards.")
st.write("One possible solution to this problem would be to adjust the menu money allocation to account not only for population density but also geographic ward size and the density of infrastructure. Another solution would be to allocate targeted aid/extra funds to these high traffic safety risk areas (such as the Far South Side) to mitigate the stark discrepancy.")


st.header("Neighborhoods, as segregated by income, also face differences in quality of education")
st.write("We know from the menu money analysis that Schools/education receive a relatively high proportion of resources across wards for 2012-2021. However, the discrepancies between educational experiences across wards is abundantly clear in the assessment outcomes. While the menu money data shows the distribution across wards of money allocated to schools and libraries, it does not immediately reveal whether these allocations translate to measurable impact on educational outcomes. In order to explore this relationship, we examined a variety of indicators of school performance from Chicago Public Schools. These include variables such as graduation and suspension rates and post-high school outcomes, as well as engagement from family and a supportive educational environment. By comparing these variables with the menu money spending on education by ward, we aim to understand whether areas that receive greater educational investment demonstrate stronger academic outcomes.")
st.altair_chart(schools_view, width='content')
st.caption("Figure 4: Quality of Education metrics aggregated by neighborhood with reference to average income and average spending on Schools & Libraries")
st.write("The Central and North Side neighborhoods have the highest average income, ranging close to 120,000. The higher-income wards are concentrated around the North Side, bordering the lakefront. The South and West sides have significantly lower average incomes. This pattern reflects Chicago’s consistently-seen socioeconomic segregation.")
st.write("When interpreting the distribution of school assessment responses across the wards, wards with consistently larger light and dark green bars than red are school districts with higher proportions of positive responses. Across all educational metrics, these are the wards that report stronger ambition, better school safety, family involvement, and supportive environments. Looking at the choropleths for income and spending on education, we can classify wards into four categories. Wards, like those in the West Side, which have both a relatively low income and low spending in education seem to perform negatively across all four assessments. Wards, like those in the North Side, which have both relatively high income and high spending in education seem to perform generally better across all four assessments. Wards in the North West Side, which have high spending on education seem to recover quality in ambition, supportive environments and high family involvement despite being below average in income. Whereas, wards with high income but low spending on education like ward 19 in the Far South Side, seem to fare relatively negatively in all categories.")
st.write("Taken together, this suggests that while income plays an important role in determining quality of education, the wards spending on the category has the ability to recover any negative impacts that can occur from a predominantly lower income population highlighting the need for wards with lower average income to receive additional support to improve their education quality. It is also clear that the general trend seen through our previous analyses of Chicago wards remains. Northern wards consistently show stronger school assessment outcomes, while several South Side wards report a high proportion of negative responses, particularly when compared relative to other wards. ")