import streamlit as st
import altair as alt
from charts.charts_crime import crimefullchart, transporttot, schools_view

st.set_page_config(page_title="Correlates", layout="wide")
st.title("Overview of Chicago Menu-Money Spending Patterns")

st.header("Correlations between race and under-resourced neighborhoods can lead to misconceived stereotypes")
st.subheader("What is the graph below addressing?")
st.write("[Stuart et al (2024)](%s) conducted a sentiment analysis on articles by the Chicago Tribune mentioning one of the 77 Chicago community areas. The sentiment analysis was then used to score the overall reputation of each community area to reflect public perception or media-propagated perception of Chicago neighborhoods. A key finding from this thorough analysis was that the reputation of a neighborhood and their status in a neighborhood hierarchy is negatively related to the proportion of black residents in the neighborhood. Adding on to this concern, they also noted that the strength of this relationship increased with time. The paper reveals the importance of media reporting in forming such perceptions. " % "https://journals.sagepub.com/doi/full/10.1177/00420980241297088")
st.write("Moreover, articles such as [this](%s) listing most “dangerous” neighborhoods in Chicago often strengthen such biases and ignore confounding variables like availability of resources to certain neighborhoods. The graph below shows how public crime rates in Chicago have changed between 2012 and 2023 along with changes in amount of money spent by the city (through the menu-money fund) overall on security cameras. This data is supplemented with a spatial analysis of race demographics, amount of money spent on security cameras per crime per person in each ward in 2021 and the total number of crimes in each ward in 2021." % "https://www.fox32chicago.com/news/chicago-most-dangerous-neighborhoods")
st.altair_chart(crimefullchart, use_container_width=True)
st.write("From looking at the top panel of the above figure we can see that while money spent on security cameras doesn’t precisely correlate with occurrences of public crimes in the Chicago area, it does closely mirror trends. Since 2012, public crimes have decline steadily while spending on security cameras steadily increased. A relationship between them is more closely observable in 2021 where spending on security cameras spiked and occurrences of public crimes dipped. It should be noted that a confounding variable of lack of police presence due to COVID-19 could have motivated the increase in security cameras and the distancing policies could have led to lower crime rates. Regardless, the relationship still illustrates that the purpose of public security cameras deployed by the city is to control crime rates and are a possible response to high crime rates")
st.write("The spatial analysis in purple indicates the distribution of different races across Chicago Wards. Not only does this analysis show how racially segregated Chicago is but also shows how marginalized communities (like African American and Hispanic populations) are even geographically marginalized to city edges. Outlining wards based on the most prevalent race would further suggest, from looking at the blue choropleth, that wards with predominantly African American populations are those with higher instances of public crimes. Such a basic analysis is what leads to misconceived perceptions as those noted earlier. A closer look at infrastructure concerns in these wards reveal that infrastructure and under-resourcing is a major confounding factor when making judgments about crime rates and race. The line graph evidently shows that infrastructure plays a role in influencing crime rates and using the data from the Chicago Menu-Money expenditure we can understand how security camera installment has further skewed crime rates. ")
st.write("The green choropleth shows how much money wards can expend on security cameras relative to the density of crime in the ward. Of the wards with the highest crime rates as seen in the blue choropleth, only two of them are in predominantly White wards. The rest are wards with predominantly African American residents. However, the same two wards (Ward 42 and Ward 27) also have a relatively high amount of money spent on security cameras per crime per person (average = 4.7). Meanwhile, the rest of the wards with relatively high crime counts, which are also predominantly African American have close to no spending on security cameras. While causal roots of this spending pattern is out of the scope of this project, we can see that lack of infrastructure is a major confounding variable when determining markers of “safe” neighborhoods. The analysis of the infrastructure features in the Chicago menu-money dataset was thus able to show how some wards are unable to adequately address pressing infrastructure concerns and suggests that equal division of infrastructure resources among wards (as they are currently drawn) is largely inequitable. ")


st.header('Even though most money is spent on Streets & Transportation + Lighting, the spending is still insufficient for some neighborhoods')
st.write("The previous section clearly indicated that certain neighborhoods are unable to meet the demands of their infrastructure concerns using menu-money alone. From the overview, we saw that these same neighborhoods (South Side, West Side and Far South Side) are unable to spare budget money on non-essential categories. If most of the budget is being allocated to expenditure on Streets & Transportation and Lighting, it begs the question on whether certain wards are over-allocating their resources to street maintenance. To see how the different neighborhoods manage their spending on Streets & Transportation + Lighting, we first looked at whether there were differences in the proportion of the budget spent on the same. Upon conducting this analysis, we noticed that the while the wards are drawn keeping in mind even population distribution, it doesn’t well take into account area leading to some wards being a lot larger than others. Furthermore, the needs of categories like Streets & Transportation and lighting would presumably scale along with size (the bigger the ward, the more streets and roads requiring maintenance). The two bar plots indicate the absolute proportional spending of the wards on the two categories and how the relative proportional spending of the wards normalized by area (in arbitrary relative units). To examine the effects of this resource allocation pattern, we examined a dataset of vehicle crashes from 2012-2023 to see the frequency of accidents caused by defects in the road or due to dark unlit roads. ")
st.altair_chart(transporttot, use_container_width=True)
st.write("here is the analysis")

st.header("Neighborhoods, as segregated by income, also face differences in quality of education")
st.altair_chart(schools_view)